site_name: Abirdotw's Public Notebook
theme:
  name: material
  palette:
    primary: lime
  features:
    - content.code.copy # render a code copy button
    - content.code.annotate # code annotations
    # - toc.integrate # 右侧生产目录
    - navigation.tracking # 在url中使用标题定位锚点
    - navigation.top # 一键回顶部
    - navigation.sections # nav节点缩进
    - navigation.tabs
    - navigation.path
# mkdocs.yml 相关配置
markdown_extensions:
  - meta
  - tables
  - footnotes # adds the ability to define inline footnotes
  - toc:
      permalink: true
      toc_depth: 4
  - admonition
  - pymdownx.details
  # CODE BLOCKS
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ["docs/3-CS/1-SD/02-PL/Python/python-programming/assignments"]
      auto_append:
        - includes/abbreviations.md
      url_download: true
  - pymdownx.superfences
  # 开始：列表
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  # 结束：列表
  - pymdownx.tabbed: # 内容标签栏
      alternate_style: true
  - md_in_html
  # Begin Tooltips
  - abbr
  - attr_list
  - pymdownx.snippets
  # End Tooltips
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic # tracking changes in documents
  - pymdownx.caret # defining sub- and superscript
  - pymdownx.tilde 
  - pymdownx.keys # keyboard keys
  - pymdownx.mark # highlighting text
  # Emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

