site_name: Abirdotw's Public Notebook
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    # - toc.integrate # 右侧生产目录
    - navigation.tracking # 在url中使用标题定位锚点
    - navigation.top # 一键回顶部
    - navigation.sections # nav节点缩进
# mkdocs.yml 相关配置
markdown_extensions:
  - tables
  - toc:
      permalink: true
      toc_depth: 4
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  # 开始：列表
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  # 结束：列表
  - pymdownx.tabbed: # 内容标签栏
      alternate_style: true
  - attr_list
  - md_in_html
  # Begin Tooltips
  - abbr
  - attr_list
  - pymdownx.snippets
  # End Tooltips
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

